title: Tukain's Blog
link: https://tukainpng.github.io
favicon: "/assets/img/fav.webp"
lang: pt-br
author: Diogo Fernandes
description: Meu blog pessoal
highlighter: rouge
markdown: kramdown
collections:
  tutorial:
    output: true
